[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
# primaryColor = "#FF6B6B"
primaryColor = "ccccff"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
